version: "3.8"
services:
  server:
    build: ./server
    container_name: api
    environment:
      - PORT=8080
      - NEIS_KEY = ${NEIS_KEY}
    ports:
      - "8080:8080"
    restart: unless-stopped

  client:
    build: ./client
    container_name: web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE = http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped
